config/routes.rb
Rails.application.routes.draw do


  resources(:articles) do
    resources :comments, only: [:create, :destroy]
  end

  resources(:subscribers, only: [:create]) do
    get "/unsubscribe/:token", action: :destroy, on: :collection, as: :unsubscribe # typically a DELETE or POST request, but when going from email clients it's best to roll with GET
    
  end


  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments

  default_scope { order(created_at: :desc) }

  def to_param
    return "#{self.id}-#{self.subject}".parameterize
  end


  def notify
    Subscriber.all.each do |sub|
      ArticleMailer.notification_email(sub, self).deliver_later
    end
  end
  handle_asynchronously :notify
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base

  before_create :generate_unsubscribe_token

  def self.subscribe(email)
    sub = Subscriber.find_or_initialize_by(email: email)

    return sub if sub.persisted?

    sub.save

    return sub
  end

  def generate_unsubscribe_token
    self.token = Digest::MD5.base64digest("#{@email}#{rand(0..100000)}")
  end

  def generate_unsubscribe_token!
    generate_unsubscribe_token
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success, :danger
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout 'darkly'

  def index
    @articles = Article.all
  end

  def show
    @article = Article.includes(:comments).find(params[:id])
    @comment = @article.comments.build
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      @article.delay.notify
      redirect_to article_url(@article), success: "Article successfully created!"
    else
      render action: :edit, danger: "Unable to create article"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    
    if @article.update_attributes(article_params)
      redirect_to article_url(@article), success: "Article sucessfully edited!"
    else
      render action: :edit, danger: "Unable to create article!"
    end
  end


  private

  def article_params
    params.require(:article).permit(:author, :subject, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def article
    @article ||= Article.find(params[:article_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.article = article

    if @comment.save 
      redirect_to :back, success: "Comment successfully posted"
    else
      render template: "articles/show", danger: "Unable to post comment"
    end

  end


  def destroy
    @comment = article.comments.find(params[:id]) 
    @comment.destroy!

    if @comment.destroyed?
      redirect_to :back, success: "Comment was successfully deleted"
    else
      redirect_to :back, danger: "Unabled to delete comment"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def create
    @subscriber = Subscriber.subscribe(subscriber_params[:email])

    if @subscriber.persisted?
      redirect_to :back, success: "You've sucessfully signed up to notifications"
    else
      redirect_to :back, danger: "Unable to subscribe to notifications"
    end
  end

  def destroy
    token = params[:token]

    @subscriber = Subscriber.find_by_token(token)
    @subscriber.destroy!

    if @subscriber.destroyed?
      redirect_to :root, success: "You're no longer subscribed :(!"
    else
      redirect_to :root, danger: "Unable to unsubscribe!"
    end
  end


  private

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def render_markdown(input)
    opts = {
      space_after_headers: true,
      link_attributes: { target: "_blank" },
      hard_wrap: true,
      filter_html: true,
      fenced_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(opts)
    md = Redcarpet::Markdown.new(renderer)

    return md.render(input).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/articles/_article.html.erb
<div class="row">
  
  <article class="col-md-12" data-id="#{article.id}">
    <h2><%= article.subject %></h2>
                                                      
    <%= render_markdown(article.body.split(" \n\n ")[0]) %>

    <%= link_to "Read full article", article_path(article) %>
  </article>
                                                      
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control", required: true %>
  </div>
                                                                                
  <div class="form-group">
    <%= f.label :subject, "Title" %>
    <%= f.text_field :subject, class: "form-control", required: true %>
  </div>
                                                                                
  <div class="form-group">
    <%= f.label :body, "Content" %>
    <%= f.text_area :body, class: "form-control", rows: "50", required: true %>
  </div>
                                                                                
  <%= f.submit (@article.new_record? ? "Post Article" : "Edit Record"), class: "btn btn-primary btn-lg" %>
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
<% end %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Edit Article</h2>
    <%= render partial: "form" %> 
  </div>

</div>

app/views/articles/index.html.erb
<section class="articles-index col-md-12">
  <header>
    <h1>Articles</h1>
  </header>
  <hr />
  
  <section class="articles-list">
    <%= render partial: "article", collection: @articles %>
  </section>


</section>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for @article do |f| %>
      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :subject, "Title" %>
        <%= f.text_field :subject, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :body, "Content" %>
        <%= f.text_area :body, class: "form-control", rows: "50", required: true %>
      </div>

      <%= f.submit "Post article", class: "btn btn-primary btn-lg" %>








    <% end %>
  </div>

</div>

app/views/articles/show.html.erb
<div class="row">
  <article class="col-md-12 article-show">
    
    <h1><%= @article.subject %></h1>
    <h5>Written by <%= @article.author %></h5>
    <hr />

    <div class="row">
    
        
      <section class="col-md-9 article-body">
        <%= render_markdown(@article.body) %>
      </section>
      
      <aside class="col-md-2 col-md-offset-1">
        <ul class="list-unstyled article-buttons">
          <li>
            <%= link_to 'Edit Article', edit_article_url(@article), class: "btn btn-large btn-primary" %>
          </li>

          <li>
            <%= link_to 'Delete Article', article_url(@article), method: :delete, class: "btn btn-large btn-danger" %>
          </li>

        </ul>
      </aside>
      
    </div>
    <hr />
    <div class="row"> 
      <section class="col-md-12 article-comments">
        <h3>Comments</h3>

        <div class="row">
          <section class="comment-list col-md-6">
            <%= render partial: "comments/comment", collection: @article.comments[0..-2] %>
          </section>
          <section class="comments-post col-md-5 col-md-offset-1">
            <%= render partial: "comments/form" %>
          </section>
        </div>
      </section>
    </div>


  </article>
  


</div>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-12">
    <article>
      <header>
        <h5>written by <strong><%= comment.author %></strong> at <time><%= comment.created_at.to_s(:short) %></time></h5>
      </header>

      <%= render_markdown comment.body %>

      <footer>
        <%= link_to "Delete", article_comment_url(comment.article, comment), method: :delete, class: "btn btn-danger btn-sm" %>
      </footer>
    </article>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for @comment, url: article_comments_url(@comment.article) do |f| %>
      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, class: "form-control", placeholder: "Your name", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :body, "Comment" %>
        <%= f.text_area :body, class: "form-control", required: true, rows: 10 %>
      </div>

      <%= f.button "Post Comment", type: :submit, class: "btn btn-primary" %>

    <% end %>

  </div>

</div>

app/views/layouts/_flash.html.erb
<%- flash.each do |key, message| %>
  <div class="alert alert-<%= key %>">
    <%= message %>
  </div>

<% end %>

app/views/layouts/_nav.html.erb
<nav>
  <div class="navbar navbar-inverse ">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MyWrite</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Articles", articles_url %></a></li>
          <li><%= link_to "Submit new article", new_article_url %></li>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mywrite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/darkly.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "mywrite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "darkly", :media => "all" %>
    <%= javascript_include_tag "darkly" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>
    <%= render partial: "layouts/nav" %>

    <div class="container">
      <%= render partial: "subscribers/form" %>
      <%= render partial: "layouts/flash" %>
      <%= yield %>
    </div>

    <%= yield(:page_javascript) if content_for?(:page_javascript) %>

    <br />
    <br />
  </body>
</html>

app/views/subscribers/_form.html.erb
<div class="jumbotron">
  <h1>Never miss another article!</h1>
  <p>Subscribe to receive email notifications as soon as a new article is posted.</p>
  <p></p>
  <%= form_for Subscriber.new do |f| %>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group form-lg">
          
          <%= f.email_field :email, class: "form-control", placeholder: "Your email address", required: true %>
        </div>
      </div>
      <div class="col-md-3">
        <%= f.button "Sign up!", type: :submit, class: "btn btn-large btn-primary" %>
      </div>
    </div>
  <%- end %>
</div>